The ``7-base_geometry`` module
============================

Test ``BaseGeometry``
---------------------

Import ``BaseGeometry`` from ``7-base_geometry`` module:

    >>> BaseGeometry = __import__('7-base_geometry').BaseGeometry

Test:

    >>> geo = BaseGeometry(None)
    Traceback (most recent call last):
    ...
    TypeError: BaseGeometry() takes no arguments

.
.

    >>> geo = BaseGeometry()

.
.

    >>> geo.area()
    Traceback (most recent call last):
    ...
    Exception: area() is not implemented

.
.

    >>> geo.area(1)
    Traceback (most recent call last):
    ...
    TypeError: area() takes 1 positional argument but 2 were given

.
.

    >>> geo.integer_validator("distance", 1)

.
.

    >>> geo.integer_validator("distance", [1, 2, 3])
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", (1, 2, 3))
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", "distance")
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", 1.5)
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", {"distance": 1})
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", None)
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", {1, 2, 3})
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", True)
    Traceback (most recent call last):
    ...
    TypeError: distance must be an integer

.
.

    >>> geo.integer_validator("distance", -3)
    Traceback (most recent call last):
    ...
    ValueError: distance must be greater than 0

.
.

    >>> geo.integer_validator("distance", 0)
    Traceback (most recent call last):
    ...
    ValueError: distance must be greater than 0

.
.

    >>> geo.integer_validator("distance")
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 1 required positional argument: 'value'

.
.

    >>> geo.integer_validator()
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() missing 2 required positional arguments: 'name' and 'value'

.
.

    >>> geo.integer_validator("my_int", 0, 1)
    Traceback (most recent call last):
    ...
    TypeError: integer_validator() takes 3 positional arguments but 4 were given
